//Last Updated: 4.21.24
//Author: derkriegs

async function create(token, {id}) {
    new Sequence()
        .effect()
        .file("jb2a.magic_signs.circle.02.conjuration.intro.dark_yellow")
        .atLocation(token)
        .scaleToObject(2)
        .belowTokens() 

        .effect()
        .file("jb2a.magic_signs.circle.02.conjuration.loop.dark_yellow")
        .atLocation(token)
        .scaleToObject(2)
        .belowTokens()
        .delay(3000)
        .duration(13000)
        .fadeOut(1000)

        .effect()
        .file("jb2a.magic_signs.rune.conjuration.complete.yellow")
        .atLocation(token, { offset: { x:70, y:22 } }) 
        .scaleToObject(0.5)
        .delay(3750)
        .playbackRate(0.65)
        .animateProperty("sprite", "position.x", { from: 0, to: -70, duration: 500, delay: 4000, ease: "easeInBack"})
        .animateProperty("sprite", "position.y", { from: 0, to: -97, duration: 500, delay: 4000, ease: "easeInBack"})
        .duration(4500)

        .effect()
        .file("jb2a.magic_signs.rune.conjuration.complete.yellow")
        .atLocation(token, { offset: { x:45, y:-61 } }) 
        .scaleToObject(0.5)
        .delay(4250)
        .playbackRate(0.65)
        .animateProperty("sprite", "position.x", { from: 0, to: -45, duration: 500, delay: 3500, ease: "easeInBack"})
        .animateProperty("sprite", "position.y", { from: 0, to: -14, duration: 500, delay: 3500, ease: "easeInBack"})
        .duration(4000)

        .effect()
        .file("jb2a.magic_signs.rune.conjuration.complete.yellow")
        .atLocation(token, { offset: { x:-45, y:-61 } }) 
        .scaleToObject(0.5)
        .delay(4750)
        .playbackRate(0.65)
        .animateProperty("sprite", "position.x", { from: 0, to: 45, duration: 500, delay: 3000, ease: "easeInBack"})
        .animateProperty("sprite", "position.y", { from: 0, to: -14, duration: 500, delay: 3000, ease: "easeInBack"})
        .zIndex(0.9)
        .duration(3500)

        .effect()
        .file("jb2a.magic_signs.rune.conjuration.complete.yellow")
        .atLocation(token, { offset: { x:-70, y:22 } }) 
        .scaleToObject(0.5)
        .delay(5250)
        .playbackRate(0.65)
        .animateProperty("sprite", "position.x", { from: 0, to: 70, duration: 500, delay: 2500, ease: "easeInBack"})
        .animateProperty("sprite", "position.y", { from: 0, to: -97, duration: 500, delay: 2500, ease: "easeInBack"})
        .zIndex(0.9)
        .duration(3000)

        .effect()
        .file("jb2a.magic_signs.rune.conjuration.complete.yellow")
        .atLocation(token, { offset: { x:0, y:75 } }) 
        .scaleToObject(0.5)
        .delay(5750)
        .playbackRate(0.65)
        .animateProperty("sprite", "position.x", { from: 0, to: 0, duration: 500, delay: 2000, ease: "easeInBack"})
        .animateProperty("sprite", "position.y", { from: 0, to: -150, duration: 500, delay: 2000, ease: "easeInBack"})
        .zIndex(0.9)
        .duration(2500)

        .effect()
        .file("jb2a.explosion.01.yellow")
        .atLocation(token, {offset: { x:5, y:-75 }})
        .scaleToObject(1.5)
        .delay(8250)
        .zIndex(1)

        .effect()
        .file("jb2a.portals.vertical.vortex.yellow")
        .atLocation(token, {offset: { x:0, y:-75} } )
        .scaleToObject(2)
        .duration(6000)
        .scaleIn({ x: 0, y: 0.8 }, 500)
        .scaleOut({ x: 0, y: 0.4}, 500, {ease: "easeInBack"})
        .fadeOut(250)
        .delay(8250)
        .zIndex(0.7)
        .belowTokens()
        .waitUntilFinished(-5750)

        .effect()
        .file("jb2a.wind_stream.1200.white")
        .atLocation(token)
        .scaleToObject(1.03)
        .rotate(90)
        .duration(6000)
        .fadeIn(250)
        .fadeOut(750)

        .effect()
        .file("jb2a.wind_stream.1200.white")
        .atLocation(token, { offset: { x:0, y: 100 }})
        .scaleToObject(1.03)
        .rotate(90)
        .duration(6000)
        .fadeIn(250)
        .fadeOut(750)

        .effect()
        .file("jb2a.energy_beam.normal.yellow.03")
        .atLocation(token, { offset: { x:0, y: 50 }})
        .rotate(90)
        .size({ width: 400, height: 350})
        .opacity(0.2)
        .duration(6000)
        .playbackRate(1.6)
        .fadeIn(250)
        .fadeOut(750)

        .animation()
        .on(token)
        .opacity(0)
        .waitUntilFinished(-500)

        .effect()
        .from(token)
        .atLocation(token)
        .animateProperty("sprite", "position.y", { from: 0, to: -15, duration: 250, ease: "easeInOutBack"})
        .waitUntilFinished(-100)

        .effect()
        .from(token)
        .atLocation(token)
        .animateProperty("sprite", "position.y", { from: -15, to: 0, duration: 2000, ease: "easeInOutBack"})
        .animateProperty("sprite", "rotation", { from: 0, to: 8, duration: 500, ease: "easeOutCubic"})
        .animateProperty("sprite", "rotation", { from: 0, to: -16, duration: 500, delay: 500, ease: "easeOutCubic"})
        .animateProperty("sprite", "rotation", { from: 0, to: 16, duration: 500, delay: 1000, ease: "easeOutCubic"})
        .animateProperty("sprite", "rotation", { from: 0, to: -16, duration: 500, delay: 1500, ease: "easeInCubic"})
        .waitUntilFinished(-100)

        .effect()
        .from(token)
        .atLocation(token)
        .animateProperty("sprite", "position.y", { from: 0, to: -40, duration: 500, ease: "easeInOutBack"})
        .waitUntilFinished(-100)

        .effect()
        .from(token)
        .atLocation(token)
        .animateProperty("sprite", "position.y", { from: -40, to: -15, duration: 2000, ease: "easeInOutBack"})
        .animateProperty("sprite", "rotation", { from: 0, to: 8, duration: 500, ease: "easeOutCubic"})
        .animateProperty("sprite", "rotation", { from: 0, to: -16, duration: 500, delay: 500, ease: "easeOutCubic"})
        .animateProperty("sprite", "rotation", { from: 0, to: 16, duration: 500, delay: 1000, ease: "easeOutCubic"})
        .animateProperty("sprite", "rotation", { from: 0, to: -16, duration: 500, delay: 1500, ease: "easeInCubic"})
        .waitUntilFinished(-100)

        .effect()
        .from(token)
        .atLocation(token)
        .animateProperty("sprite", "position.y", { from: -15, to: -200, duration: 750, ease: "easeInOutBack"})
        .scaleOut(0, 750)
        .duration(375)
        .waitUntilFinished(-150)

        .effect()
        .file("animated-spell-effects-cartoon.flash.01")
        .atLocation(token, {offset: { x:0, y:-85 }})
        .scaleToObject(0.5)
        .filter("ColorMatrix", { hue: 15 } )
        .zIndex(0.9)

        .effect()
        .file("jb2a.detect_magic.cone.yellow")
        .rotateTowards(token)
        .atLocation(token, {offset: { x:0, y:-110 }})
        .scaleToObject(1)
        .playbackRate(1.5)
        .zIndex(1)

        .effect()
        .file("jb2a.template_circle.out_pulse.02.loop.yellowwhite")
        .atLocation(token, { offset: { x:0, y:-75 }})
        .scaleToObject(1.75)
        .delay(1000)
        .fadeOut(1000)
        .waitUntilFinished(-1500)

        .effect()
        .file("jb2a.fireflies.many.02.yellow")
        .atLocation(token, { offset: { x:0, y:-75 }})
        .scaleToObject(0.75)
        .duration(2000)
        .fadeIn(500)
        .fadeOut(750)
        .animateProperty("sprite", "position.y", { from: 0, to: 75, duration: 3000})

        .play();
}

async function destroy(token) {
    new Sequence()
        .animation()
        .on(token)
        .opacity(1)
        .fadeIn(1000)
        .play();
}